# Exam Practice: ResourceQuota
# Limits namespace resource usage for pods and PVCs
#
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: limited
spec:
  hard:
    pods: "2"
    requests.cpu: "1"
    requests.memory: 1Gi
