# Secret for Database Credentials
# Stores base64-encoded database username and password securely
#
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: YWRtaW4=        # base64 encoded "admin"
  password: c2VjcmV0MTIz    # base64 encoded "secret123"
