apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  completions: 3
  parallelism: 2
  template:
    spec:
      containers:
        - name: worker
          image: busybox:latest
          command: ['sh', '-c', 'echo "Working..."; sleep 5; echo "Complete"']
      restartPolicy: Never
  backoffLimit: 4
