# PersistentVolumeClaim
# Requests 500Mi of storage that binds to available PersistentVolume
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
