# Pod with Mounted PVC
# Creates pod that mounts and uses a PersistentVolumeClaim for data storage
#
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: storage
      mountPath: /data
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc-local
