apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: foodcart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
      role: backend
  template:
    metadata:
      labels:
        app: payments
        role: backend
    spec:
      containers:
      - name: payments
        image: python:3.11-slim
        command: ["python", "-m", "http.server", "8080"]
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        envFrom:
        - secretRef:
            name: postgres-secret
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: foodcart
spec:
  selector:
    app: payments
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
