# Simple nginx Pod
# Creates a basic pod running nginx web server on port 80
#
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
