# Pod with Startup Probe
# Delays liveness/readiness checks for slow-starting applications
#
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-startup
spec:
  containers:
  - name: app
    image: nginx
    ports:
    - containerPort: 8080
    startupProbe:
      httpGet:
        path: /startup
        port: 8080
      failureThreshold: 30
      periodSeconds: 10
