# Pod with NodeSelector
# Schedules pod only on nodes labeled with disktype=ssd
#
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-node-selector
spec:
  nodeSelector:
    disktype: ssd
  containers:
  - name: nginx
    image: nginx
