repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-added-large-files

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [-c, k8s-runbook-labs/.yamllint.yml]
        files: ^k8s-runbook-labs/.*\.(yaml|yml)$

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [-c, k8s-runbook-labs/.markdownlint.json]
        files: ^k8s-runbook-labs/.*\.md$
