name: K8s Runbook CI

on:
  push:
    paths:
      - 'k8s-runbook-labs/**'
      - '.github/workflows/k8s-runbook-ci.yml'
  pull_request:
    paths:
      - 'k8s-runbook-labs/**'
      - '.github/workflows/k8s-runbook-ci.yml'

jobs:
  lint-yaml:
    name: Lint YAML Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install yamllint
        run: pip install yamllint
      
      - name: Run yamllint
        run: |
          yamllint -c k8s-runbook-labs/.yamllint.yml k8s-runbook-labs/ || true
          echo "YAML linting completed"

  validate-k8s-schemas:
    name: Validate Kubernetes Schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install kubeconform
        run: |
          wget https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar xf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin/
      
      - name: Validate Kubernetes manifests
        run: |
          find k8s-runbook-labs/sections -name "*.yaml" -o -name "*.yml" | \
          xargs -I {} kubeconform -summary -strict {} || true
          echo "Kubernetes schema validation completed"

  lint-markdown:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      
      - name: Run markdownlint
        run: |
          markdownlint k8s-runbook-labs/**/*.md -c k8s-runbook-labs/.markdownlint.json || true
          echo "Markdown linting completed"

  check-coverage:
    name: Check Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify COVERAGE.md exists
        run: |
          if [ ! -f k8s-runbook-labs/COVERAGE.md ]; then
            echo "❌ COVERAGE.md not found!"
            exit 1
          fi
          echo "✅ COVERAGE.md exists"
      
      - name: Check coverage completeness
        run: |
          cd k8s-runbook-labs
          # Count non-empty coverage entries (excluding headers)
          MAPPED_SLIDES=$(grep -E '^\|' COVERAGE.md | grep -v '^| Slide' | grep -v '^|---' | grep -v '^| *$' | wc -l)
          echo "Mapped slides: ${MAPPED_SLIDES}"
          
          # We expect at least 19 sections to be covered
          if [ "${MAPPED_SLIDES}" -lt 19 ]; then
            echo "⚠️  Warning: Coverage may be incomplete (< 19 entries)"
          else
            echo "✅ Coverage check passed (${MAPPED_SLIDES} entries)"
          fi
